workflows:
  kmp-workflow:
    name: KMP Build & Test Lab
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'feature/codemagic-pipeline'
          include: true
          source: true
    environment:
      groups:
        - FIREBASE_DAILYPULSE
    scripts:
      - name: Set up Service Account
        script: |
          echo "$GCLOUD_SERVICE_ACCOUNT_KEY" | base64 --decode > ./gcloud_key.json
      - name: Build Android & iOS (KMP)
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Run Tests on Firebase Test Lab
        script: |
          gcloud auth activate-service-account --key-file=./gcloud_key.json
          gcloud --quiet config set project daily-pulse-kmp
          gcloud firebase test android run --app build/outputs/apk/debug/app-debug.apk